### ISSUE TITLE
Make applikatoni easy to use

### ISSUE THREAD

**Issue by NamPNQ** [applikatoni/applikatoni#26]
Hi

Correct me if I get wrong.

I think not all users store their code in github, then I have idea. 
We will support login from google. Code store in somewhere support, when deploy, we pull code, and restart monitor app, ex: supervisorctl restart app

**Comment by mrnugget** [comment]
Yep, we thought about the same thing before.

I have the idea to add the ability for other "providers" and deployment techniques: Google Code, Docker containers, and so on. Different sources besides GitHub so to speak. The underlying engine in Applikatoni, the `deploy` package, doesn't really care about all that. The only difference is that instead of injecting a SHA we'd need to inject a Docker URL or something into the script templates when rendering them.

Besides the deployment engine, of course, the frontend would need to be much more general. At the moment it's tailored to GitHub, branches, pull requests. A different frontend for a Google Code, Docker registry and so on would be needed.

At the moment we host all our code on GitHub and I don't know if there is sufficient need for another provider. So that's something I put on the backlog.

**Comment by NamPNQ** [comment]
Oh, If u agree I will work for make pr to support local git repo and support localhost in hosts

**Comment by mrnugget** [comment]
I don't think supporting localhost is going to be an easy task: Applikatoni works on the assumption that it needs to connect to other servers via SSH. That's deeply integrated into the "engine".

And I don't think it makes sense for Applikatoni to deploy system on the same server from a local git repository. There are far better tools that can solve these problems than this one.
