### ISSUE TITLE
Deploy in localhost

### ISSUE THREAD

**Issue by NamPNQ** [applikatoni/applikatoni#32]
I only have one server, I setup applikatoni and web app in this, how to config

**Comment by mrnugget** [comment]
You need an SSH server running locally if you want to connect to your localhost. I think @Wind0r has Applikatoni running locally and connecting to localhost, maybe he can chime in.

But, just a reminder: this is not what Applikatoni is built for. It's supposed to be used on a different machine, that is connecting to application/whatever-servers and then execute stages of deployments there. So it's possible that you're going to run into other problems.

**Comment by NamPNQ** [comment]
@Wind0r Why we not choose os/exec instead of ssh locally

**Comment by Wind0r** [comment]
Yes. For testing/developing my applikatoni only connects to localhost. There isnt any problem and it is easy.

@NamPNQ because ssh is implemented and os/exec not ;)
I also see no advantage to implemented it.
Using os/exec will even get you a lot of problems.
e.g. to restart services applikatoni need to be run as root.

**Comment by mrnugget** [comment]
I think the comment by @Wind0r answers your question. If it doesn't or you have any more questions, we can reopen ticket.
