### ISSUE TITLE
Gitlab / Gitlab CI integration

### ISSUE THREAD

**Issue by sammcj** [applikatoni/applikatoni#4]
It would be amazing if you could use Applikatoni with Gitlab as it's also great to run self-hosted and Gitlab-CI is a really nice, simple integrated CI system.

Love the app, well done!

**Comment by mrnugget** [comment]
Thanks! Glad you like it :)

As for the integration of Gitlab: I've had that same idea, but since we're not using Gitlab in production at the moment I don't have the necessary use case for it. That doesn't mean that it'll never happen, it's just not on the roadmap for the near future. But if someone was to open a pull request that adds Gitlab (and Gitlab-CI) integration, I'd happily merge it.

What would need to be changed/added? 

* We'd need a Gitlab client/adapter [like the GitHub one](https://github.com/applikatoni/applikatoni/blob/eb77fcc0d22f85735436dc5c1a8b3d05fbe01d16/server/github.go). That shouldn't be too hard.
* [The two handlers, that take care of branches and pull requests,](https://github.com/applikatoni/applikatoni/blob/eb77fcc0d22f85735436dc5c1a8b3d05fbe01d16/server/handlers.go#L106-L147) would need to use the correct adapter/client.
* Every use of `GitHubOwner` and `GitHubRepo` (fields of the `Application` struct)  need to be changed to use the correct fields. A simple grep shows, that there are "only" 16 of such mentions. And these are mostly purely cosmetic (for constructing links and so on)

And if someone were to do this, I'd propose to make this change more general, so that instead of configuring a `github_owner` and `github_repo` we'd configure a `repository_host` or something like that.

Maybe I'll do this myself sometime in the future. But at the moment the top priority items on my list concern a better GitHub integration: show diffs pulled from GitHub before deploying, link to diffs, post deployment status to pull requests and so on...

How does that sound?

**Comment by mrnugget** [comment]
I'll close this for now.
